"""adding jobinfo and job table

Revision ID: 06f4fe3d2871
Revises: dbd0a5718cb7
Create Date: 2022-11-23 11:08:08.436923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f4fe3d2871'
down_revision = 'dbd0a5718cb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('skills', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_information_id'), 'jobs_information', ['id'], unique=False)
    op.create_index(op.f('ix_jobs_information_job_description'), 'jobs_information', ['job_description'], unique=False)
    op.create_index(op.f('ix_jobs_information_skills'), 'jobs_information', ['skills'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs_information.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_jobs_information_skills'), table_name='jobs_information')
    op.drop_index(op.f('ix_jobs_information_job_description'), table_name='jobs_information')
    op.drop_index(op.f('ix_jobs_information_id'), table_name='jobs_information')
    op.drop_table('jobs_information')
    # ### end Alembic commands ###
