"""create and rename fields in users

Revision ID: 4224f130e53f
Revises: 3bb15e6cca05
Create Date: 2022-11-23 21:22:50.246304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4224f130e53f'
down_revision = '3bb15e6cca05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
