"""create prosze napraw sie

Revision ID: 44d46c86c035
Revises: e967d15eaa9c
Create Date: 2023-01-04 21:51:01.709251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d46c86c035'
down_revision = 'e967d15eaa9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_audit', 'stamp',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('user_audit', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_audit', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('user_audit', 'stamp',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
