"""create all tables

Revision ID: 524de93c3102
Revises: 
Create Date: 2023-01-28 15:04:44.453768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524de93c3102'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_description', sa.String(), nullable=True),
    sa.Column('establishment_date', sa.Date(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('job_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_location_id'), 'job_location', ['id'], unique=False)
    op.create_table('job_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_type_id'), 'job_type', ['id'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_name')
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_table('user_audit',
    sa.Column('stamp', sa.DateTime(), nullable=False),
    sa.Column('operation', sa.String(length=1), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('stamp')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('api_keys',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_index(op.f('ix_api_keys_api_key'), 'api_keys', ['api_key'], unique=True)
    op.create_index(op.f('ix_api_keys_company_id'), 'api_keys', ['company_id'], unique=False)
    op.create_table('employee_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['company.company_name'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_employee_profile_company'), 'employee_profile', ['company'], unique=False)
    op.create_index(op.f('ix_employee_profile_user_id'), 'employee_profile', ['user_id'], unique=False)
    op.create_table('job_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('job_type_id', sa.Integer(), nullable=True),
    sa.Column('job_location_id', sa.Integer(), nullable=True),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('taken_by_id', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_location_id'], ['job_location.id'], ),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_type.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_post_id'), 'job_post', ['id'], unique=False)
    op.create_index(op.f('ix_job_post_job_location_id'), 'job_post', ['job_location_id'], unique=False)
    op.create_index(op.f('ix_job_post_job_type_id'), 'job_post', ['job_type_id'], unique=False)
    op.create_index(op.f('ix_job_post_posted_by_id'), 'job_post', ['posted_by_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['employee_profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.create_index(op.f('ix_employee_skills_skill_id'), 'employee_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_user_id'), 'employee_skills', ['user_id'], unique=False)
    op.create_table('job_post_skill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skill_id', 'job_post_id')
    )
    op.create_index(op.f('ix_job_post_skill_job_post_id'), 'job_post_skill', ['job_post_id'], unique=False)
    op.create_index(op.f('ix_job_post_skill_skill_id'), 'job_post_skill', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_post_skill_skill_id'), table_name='job_post_skill')
    op.drop_index(op.f('ix_job_post_skill_job_post_id'), table_name='job_post_skill')
    op.drop_table('job_post_skill')
    op.drop_index(op.f('ix_employee_skills_user_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_skill_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_job_post_posted_by_id'), table_name='job_post')
    op.drop_index(op.f('ix_job_post_job_type_id'), table_name='job_post')
    op.drop_index(op.f('ix_job_post_job_location_id'), table_name='job_post')
    op.drop_index(op.f('ix_job_post_id'), table_name='job_post')
    op.drop_table('job_post')
    op.drop_index(op.f('ix_employee_profile_user_id'), table_name='employee_profile')
    op.drop_index(op.f('ix_employee_profile_company'), table_name='employee_profile')
    op.drop_table('employee_profile')
    op.drop_index(op.f('ix_api_keys_company_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_api_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_audit')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_job_type_id'), table_name='job_type')
    op.drop_table('job_type')
    op.drop_index(op.f('ix_job_location_id'), table_name='job_location')
    op.drop_table('job_location')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
