"""refresh

Revision ID: 57aee4ab5502
Revises: 
Create Date: 2022-12-29 18:27:46.363306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57aee4ab5502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_description', sa.String(), nullable=True),
    sa.Column('establishment_date', sa.Date(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_table('job_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_location_id'), 'job_location', ['id'], unique=False)
    op.create_table('job_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_type_id'), 'job_type', ['id'], unique=False)
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_id'), 'skill', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('employee_profile',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_employee_profile_user_id'), 'employee_profile', ['user_id'], unique=False)
    op.create_table('job_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('posted_by_id', sa.Integer(), nullable=True),
    sa.Column('job_type_id', sa.Integer(), nullable=True),
    sa.Column('job_location_id', sa.Integer(), nullable=True),
    sa.Column('job_description', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_location_id'], ['job_location.id'], ),
    sa.ForeignKeyConstraint(['job_type_id'], ['job_type.id'], ),
    sa.ForeignKeyConstraint(['posted_by_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_post_id'), 'job_post', ['id'], unique=False)
    op.create_index(op.f('ix_job_post_job_location_id'), 'job_post', ['job_location_id'], unique=False)
    op.create_index(op.f('ix_job_post_job_type_id'), 'job_post', ['job_type_id'], unique=False)
    op.create_index(op.f('ix_job_post_posted_by_id'), 'job_post', ['posted_by_id'], unique=False)
    op.create_table('employee_skills',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['employee_profile.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'skill_id')
    )
    op.create_index(op.f('ix_employee_skills_skill_id'), 'employee_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_employee_skills_user_id'), 'employee_skills', ['user_id'], unique=False)
    op.create_table('job_post_skill',
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('job_post_id', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_post_id'], ['job_post.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ),
    sa.PrimaryKeyConstraint('skill_id', 'job_post_id')
    )
    op.create_index(op.f('ix_job_post_skill_job_post_id'), 'job_post_skill', ['job_post_id'], unique=False)
    op.create_index(op.f('ix_job_post_skill_skill_id'), 'job_post_skill', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_post_skill_skill_id'), table_name='job_post_skill')
    op.drop_index(op.f('ix_job_post_skill_job_post_id'), table_name='job_post_skill')
    op.drop_table('job_post_skill')
    op.drop_index(op.f('ix_employee_skills_user_id'), table_name='employee_skills')
    op.drop_index(op.f('ix_employee_skills_skill_id'), table_name='employee_skills')
    op.drop_table('employee_skills')
    op.drop_index(op.f('ix_job_post_posted_by_id'), table_name='job_post')
    op.drop_index(op.f('ix_job_post_job_type_id'), table_name='job_post')
    op.drop_index(op.f('ix_job_post_job_location_id'), table_name='job_post')
    op.drop_index(op.f('ix_job_post_id'), table_name='job_post')
    op.drop_table('job_post')
    op.drop_index(op.f('ix_employee_profile_user_id'), table_name='employee_profile')
    op.drop_table('employee_profile')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skill_id'), table_name='skill')
    op.drop_table('skill')
    op.drop_index(op.f('ix_job_type_id'), table_name='job_type')
    op.drop_table('job_type')
    op.drop_index(op.f('ix_job_location_id'), table_name='job_location')
    op.drop_table('job_location')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
