"""add cascade 2

Revision ID: 59a2d5a589e9
Revises: a36c724acb65
Create Date: 2023-01-11 21:57:15.648501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a2d5a589e9'
down_revision = 'a36c724acb65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('employee_profile_company_fkey', 'employee_profile', type_='foreignkey')
    op.create_foreign_key(None, 'employee_profile', 'company', ['company'], ['company_name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_profile', type_='foreignkey')
    op.create_foreign_key('employee_profile_company_fkey', 'employee_profile', 'company', ['company'], ['company_name'])
    # ### end Alembic commands ###
