"""add company field

Revision ID: 78ab34b68cf6
Revises: 57aee4ab5502
Create Date: 2022-12-30 14:06:46.715365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ab34b68cf6'
down_revision = '57aee4ab5502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'company', ['company_name'])
    op.add_column('employee_profile', sa.Column('company', sa.String(), nullable=True))
    op.create_index(op.f('ix_employee_profile_company'), 'employee_profile', ['company'], unique=False)
    op.create_foreign_key(None, 'employee_profile', 'company', ['company'], ['company_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_profile', type_='foreignkey')
    op.drop_index(op.f('ix_employee_profile_company'), table_name='employee_profile')
    op.drop_column('employee_profile', 'company')
    op.drop_constraint(None, 'company', type_='unique')
    # ### end Alembic commands ###
