"""create cascade

Revision ID: c3c4e8206d76
Revises: c5d5d3090f12
Create Date: 2023-01-04 21:43:18.222417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3c4e8206d76'
down_revision = 'c5d5d3090f12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_audit')
    op.drop_constraint('employee_profile_user_id_fkey', 'employee_profile', type_='foreignkey')
    op.create_foreign_key(None, 'employee_profile', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_profile', type_='foreignkey')
    op.create_foreign_key('employee_profile_user_id_fkey', 'employee_profile', 'users', ['user_id'], ['id'])
    op.create_table('user_audit',
    sa.Column('operation', sa.CHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('userid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
