"""add salary and unique to skill

Revision ID: c5d5d3090f12
Revises: fb16a423c820
Create Date: 2023-01-03 21:00:19.945873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5d5d3090f12'
down_revision = 'fb16a423c820'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('salary', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'skill', ['skill_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='unique')
    op.drop_column('job_post', 'salary')
    # ### end Alembic commands ###
