"""add table useraudit

Revision ID: e967d15eaa9c
Revises: c3c4e8206d76
Create Date: 2023-01-04 21:49:26.028853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e967d15eaa9c'
down_revision = 'c3c4e8206d76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=1), nullable=True),
    sa.Column('stamp', sa.Date(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_audit')
    # ### end Alembic commands ###
