"""add employee_id to job_post

Revision ID: f7a212eb4068
Revises: 5900243f771c
Create Date: 2023-01-02 10:57:35.036585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a212eb4068'
down_revision = '5900243f771c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('taken_by_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post', 'taken_by_id')
    # ### end Alembic commands ###
