"""add default value to job_post_taken

Revision ID: fb16a423c820
Revises: f7a212eb4068
Create Date: 2023-01-02 11:14:40.851610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb16a423c820'
down_revision = 'f7a212eb4068'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
